# Generated by Django 4.2.17 on 2025-01-06 11:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
