# Generated by Django 4.2.17 on 2025-01-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_image'),
        ('testimonials', '0002_testimonial_approved_testimonial_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='rooms.room'),
        ),
    ]
