# Generated by Django 4.2.17 on 2025-01-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_blockroom_end_date_blockroom_start_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockRoom',
        ),
    ]
